server:
  rootPath: /api/

# Database settings.
database:
    driverClass: com.mysql.jdbc.Driver
    # user: pdizzydawg
    # password: uw89duKf2swrVE49FAgA
    user: root
    password: 
    url: jdbc:mysql://localhost:3306/beyondbrackets
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.hbm2ddl.auto: validate

logging:
  level: INFO
  loggers:
    io.beyondbrackets: DEBUG
