server:
  rootPath: /api/

# Database settings.
database:
    driverClass: com.mysql.jdbc.Driver
    user: root
    password:
    url: jdbc:mysql://localhost:3306/beyondbrackets
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.hbm2ddl.auto: create-drop

logging:
  level: INFO
  loggers:
    io.beyondbrackets: DEBUG
